version: 2.1

commands:
  install-arm-none-eabi:
    steps:
      - run:
        name: Install GNU Toolchain for the A-profile Architecture, aarch32
        command: |
          sudo apt update
          sudo apt-get install -y curl
          curl -LO https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz
          sudo tar -C /usr/local -xvf gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz
          rm gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz

# see https://github.com/harfbuzz/harfbuzz/blob/main/.circleci/config.yml for inspiration
jobs:
  crossbuild-ubuntu:
    docker:
      - image: ubuntu:rolling
    environment:
      PATH: $PWD/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi:$PATH
    steps:
      - install-arm-none-eabi
      - checkout
      - run: make clean all

workflows:
  version: 2

  build:
    jobs:
      - crossbuild-ubuntu
